version: '3'
services:
  geth1:
    image: "chainsafe/chainbridge-geth:latest"
    container_name: geth1
    ports:
    - "8545:8545"
    
  sub-chain:
    image: "chainsafe/chainbridge-substrate-chain:v1.2.0"
    container_name: sub-chain
    command: chainbridge-substrate-chain --dev --alice --ws-external --rpc-external
    ports:
    - "9944:9944"
