FROM golang:1.14-alpine

RUN apk add --no-cache git gcc musl-dev linux-headers && \
    git clone https://github.com/ChainSafe/ChainBridge && \
    cd /go/ChainBridge/cmd/chainbridge && \
    go build

COPY config.json config.json
COPY chainbridge.sh chainbridge.sh

ENTRYPOINT ./chainbridge.sh
